# https://taskfile.dev

version: '3'

tasks:
  install:
    desc: 'Installs everything needed to start the project'
    cmds:
      - echo "your commands go here!"
  run:
    desc: 'Runs the project'
    cmds:
      - echo "your commands go here!"
  update:
    desc: 'Updates docker containers, packages, etc.'
    cmds:
      - echo "your commands go here!"
  stop:
    desc: "Stop the project"
    cmds:
      - echo "your commands go here!"
  test:
    desc: "Run all tests"
    cmds:
      - echo "your commands go here!"
