# https://taskfile.dev

version: '3'

vars:
  INSTALL: >
    The install task will install dependencies (npm, virtualenv, …), and make sure an initial config exists.
  UPDATE: >
    Will use the necessary tools to make sure the project is up to date. 
    This means for example running database migrations..
  RUN: >
    Starts the local development server, most of the time we will use something like http://localhost:8000/ for this. 
    The development server may be started inside a docker container using docker-compose.
  STOP: >
    Stops the project (`npm run` commands, detached running docker containers, etc.)

tasks:
  install:
    desc: '{{.INSTALL}}'
    cmds:
      - echo "Enter custom install commands here"

  update:
    desc: '{{.UPDATE}}'
    cmds:
      - echo "Enter custom update commands here"

  run:
    desc: '{{.RUN}}'
    cmds:
      - echo "Enter custom run commands here"

  stop:
    desc: "{{.STOP}}"
    cmds:
      - echo "Enter custom stop commands here"